### ISSUE TITLE
Display Colour

### ISSUE THREAD

**Issue by Lazarus00001** [penglezos/device_xiaomi_raphael#35]
Display colours r more faded in NATURAL and BOOSTED profile

**Comment by penglezos** [comment]
Compared to the previous color calibration file yes and that's because the previous one was using display features from Google Pixel device which were boosted by default and not the stock ones. I don't think the new ones are too washed out for day to day usage. Boosted color profile boost colors as intended.

**Comment by Lazarus00001** [comment]
Default adaptive color profile is perfect I m talking about other 2 
In my eyes natural and boosted looks like fade after using adaptive, although it's not a bug, if possible please add previous color setting

**Comment by penglezos** [comment]
I've just explained to you why natural color mode looks washed out for you and adaptive not compared to the previous color calibration configuration. All AOSP roms using the previous one are having over saturated colors on Natural color mode that's why you like it. It is possible for me to fine tune the current one but not return to the previous one which is wrong. Also natural color mode should show the most accurate colors available to the display panel and not boost them according to Google documentation.

**Comment by Lazarus00001** [comment]
Okay, after using natural color for an hour I feel it's more comfortable for my eye.
Can u add anti flicker in feature?
