### ISSUE TITLE
Fingerprint sensor misbehaving in Extra Dim or Night Light mode

### ISSUE THREAD

**Issue by KrustyKrabCoder** [penglezos/device_xiaomi_raphael#41]
#### Description:
The fingerprint sensor is not reading the finger correctly when the phone is in Extra Dim or Night Light mode, or both combined. The success rate of the fingerprint recognition is significantly lower, and the process is slower than usual.

#### Steps to reproduce:
1. Activate Extra Dim or Night Light mode (or both simultaneously).
2. Attempt to unlock the device using the fingerprint sensor.
3. Observe that the sensor's recognition accuracy and speed are reduced.

#### Expected behavior:
Fingerprint sensor should operate with the same accuracy and speed, regardless of Extra Dim or Night Light modes.

#### Build info:
- Affected build: `lineage-21.0-20240909-UNOFFICIAL-raphael`

**Comment by penglezos** [comment]
Hi @KrustyKrabCoder,

I use Night Light daily and I can unlock my device via fingerprint sensor without any accuracy issues whatsoever even on the highest intensity available. On the other hand Extra Dim is indeed causing accuracy problems since our device uses an optical fingerprint sensor which expects light to be emitted in order to register the actual fingerprint blueprint and this feature dims the brightness. I suggest you to upscale the intensity of Extra Dim to the right spot,  meanwhile I can disable Extra Dim functionality on lockscreen or when fingerprint sensor is pressed (not sure how this is going to react).

**Comment by KrustyKrabCoder** [comment]
Hello @penglezos,

Thank you for your prompt response! 

I was wondering if it would be possible to disable night mode and extra dim specifically for the screen area used for illumination. In my case, night mode works at lower intensity levels, but at higher levels, it doesn’t seem to function properly. This might be related to my skin tone or other factors like OLED burn-in. 

Without night mode, everything works perfectly, so I hope this solution wouldn't cause issues for others.

Thanks again!
